//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

pub use super::friendships::Entity as Friendships;
pub use super::user_attribute_history::Entity as UserAttributeHistory;
pub use super::user_location_history::Entity as UserLocationHistory;
pub use super::users::Entity as Users;
